[features]
seeds = false
skip-lint = false
[programs.devnet] # Changed from localnet to devnet
liquidity_pool = "GL6uWvwZAapbf54GQb7PwKxXrC6gnjyNcrBMeAvkh7mg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet" # Changed cluster to Devnet
wallet = "temp_devnet_wallet.json" # Point to the temporary wallet file

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
